apiVersion: v1
kind: Secret
metadata:
  name: fcg-catalog-worker-secret
type: Opaque
stringData:
    ConnectionStrings__DefaultConnection: "Host=host.docker.internal;Port=5432;Database=devCatalog;Username=postgres;Password=mysecretpassword"
    RabbitMQ__Host: fcgpayments-rabbitmq-svc
    RabbitMQ__VirtualHost: "my_vhost"
    RabbitMQ__Username: user
    RabbitMQ__Password: senha