apiVersion: v1
kind: Secret
metadata:
  name: fcg-catalog-worker-secret
type: Opaque
stringData:
    ConnectionStrings__DefaultConnection: "Host=fcgcatalog-postgres-svc;Port=5432;Database=;Username=;Password="
    RabbitMQ__Host: fcgcatalog-rabbitmq-svc
    RabbitMQ__VirtualHost: "my_vhost"
    RabbitMQ__Username: usuario
    RabbitMQ__Password: senha